species: Puma concolor

genome: "data/genome/GCF_003327715.1_PumCon1.0_genomic.fna"
    #https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/327/715/GCF_003327715.1_PumCon1.0/GCF_003327715.1_PumCon1.0_genomic.fna.gz

popmap: "data/popmap.tsv"

process_radtags:
    enzyme1: nlaIII
    enzyme2: ecoRI
    # adapter_mm : 2
    # adapter_1 : ACACTCTTTCCCTACACGACGCTCTTCCGATCT,AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT,GATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCAGAACAA,CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCC
    # adapter_2 : ACACTCTTTCCCTACACGACGCTCTTCCGATCT,AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT,GATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCAGAACAA,CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCC
